#include "TestHarness.h"
#include "world/coordinates/Coords.h"
#include "world/coordinates/StickyGroupAnchor.h"
#include "world/coordinates/WorldPosition.h"
#include <cstdint>
#include <limits>
TEST_CASE(canonical_carry_crosses_all_levels){using namespace world;BlockAddress a{};a.chunk.group.sector={10,10,10};a.chunk.group.region={REGIONS_PER_SECTOR_EDGE-1,REGIONS_PER_SECTOR_EDGE-1,REGIONS_PER_SECTOR_EDGE-1};a.chunk.group.section={SECTIONS_PER_REGION_EDGE-1,SECTIONS_PER_REGION_EDGE-1,SECTIONS_PER_REGION_EDGE-1};a.chunk.group.group={GROUPS_PER_SECTION_EDGE-1,GROUPS_PER_SECTION_EDGE-1,GROUPS_PER_SECTION_EDGE-1};a.chunk.chunk={CHUNKS_PER_GROUP_EDGE-1,CHUNKS_PER_GROUP_EDGE-1,CHUNKS_PER_GROUP_EDGE-1};a.block={BLOCKS_PER_CHUNK_EDGE-1,BLOCKS_PER_CHUNK_EDGE-1,BLOCKS_PER_CHUNK_EDGE-1};const auto b=offsetBlock(a,1,1,1);CHECK_EQ(b.chunk.group.sector.x,11);CHECK_EQ(b.chunk.group.region.x,0);CHECK_EQ(b.chunk.group.section.x,0);CHECK_EQ(b.chunk.group.group.x,0);CHECK_EQ(b.chunk.chunk.x,0);CHECK_EQ(b.block.x,0);CHECK(offsetBlock(b,-1,-1,-1)==a);}
TEST_CASE(section_is_65536_blocks_wide_with_default_physical_radices){using namespace world;CHECK_EQ(GROUPS_PER_SECTION_EDGE,256);CHECK_EQ(BLOCKS_PER_GROUP_EDGE,256);const auto last=fromOriginOffset(65535,0,0);CHECK_EQ(last.chunk.group.section.x,0);CHECK_EQ(last.chunk.group.group.x,255);CHECK_EQ(last.chunk.chunk.x,15);CHECK_EQ(last.block.x,15);const auto next=offsetBlock(last,1,0,0);CHECK_EQ(next.chunk.group.section.x,1);CHECK_EQ(next.chunk.group.group.x,0);}
TEST_CASE(origin_offsets_handle_negative_values){using namespace world;const auto a=fromOriginOffset(-1,-17,-257);const auto o=originBlockAddress();RelativeI64 d{};CHECK(blockDeltaWithin(a,o,300,d));CHECK_EQ(d.x,-1);CHECK_EQ(d.y,-17);CHECK_EQ(d.z,-257);}
TEST_CASE(relative_delta_across_sector_seam_is_small){using namespace world;BlockAddress a{};a.chunk.group.sector.x=5;a.chunk.group.region.x=REGIONS_PER_SECTOR_EDGE-1;a.chunk.group.section.x=SECTIONS_PER_REGION_EDGE-1;a.chunk.group.group.x=GROUPS_PER_SECTION_EDGE-1;a.chunk.chunk.x=CHUNKS_PER_GROUP_EDGE-1;a.block.x=BLOCKS_PER_CHUNK_EDGE-1;const auto b=offsetBlock(a,1,0,0);RelativeI64 d{};CHECK(blockDeltaWithin(b,a,1,d));CHECK_EQ(d.x,1);}
TEST_CASE(world_position_keeps_fraction_at_huge_sector){using namespace world;BlockAddress a{};a.chunk.group.sector={8000000000000000000LL,0,-8000000000000000000LL};a.chunk.group.region={7000000000000000000LL,0,1};a.chunk.group.section={6000000000000000000LL,2,3};WorldPosition p=WorldPosition::fromBlockAddress(a,0.75f,0.25f,0.5f);p.translate(0.5,0.0,0.0);CHECK_EQ(p.blockAddress().block.x,1);CHECK(std::abs(p.fractionX()-0.25f)<1e-6f);const auto local=p.relativeToGroup(p.group());CHECK(local.x>=1.0f&&local.x<2.0f);}
TEST_CASE(top_sector_overflow_never_wraps){using namespace world;BlockAddress a{};a.chunk.group.sector.x=std::numeric_limits<std::int64_t>::max();a.chunk.group.region.x=REGIONS_PER_SECTOR_EDGE-1;a.chunk.group.section.x=SECTIONS_PER_REGION_EDGE-1;a.chunk.group.group.x=GROUPS_PER_SECTION_EDGE-1;a.chunk.chunk.x=CHUNKS_PER_GROUP_EDGE-1;a.block.x=BLOCKS_PER_CHUNK_EDGE-1;BlockAddress out{};CHECK(!tryOffsetBlock(a,1,0,0,out));}
TEST_CASE(group_local_block_mapping_stays_small){using namespace world;BlockAddress a{};a.chunk.group.sector={8000000000000000000LL,-8,-8000000000000000000LL};a.chunk.group.region={7000000000000000000LL,1,2};a.chunk.group.section={6000000000000000000LL,3,4};a.chunk.chunk={15,7,3};a.block={15,4,12};const LocalGroupBlockCoord local=localBlockInGroup(a);CHECK_EQ(local.x,255);CHECK_EQ(local.y,116);CHECK_EQ(local.z,60);}

TEST_CASE(hierarchy_navigation_preserves_lower_digits){using namespace world;BlockAddress a{};a.chunk.group.sector={4,5,6};a.chunk.group.region={7,8,9};a.chunk.group.section={10,11,12};a.chunk.group.group={13,14,15};a.chunk.chunk={2,3,4};a.block={5,6,7};const auto chunk=offsetHierarchy(a,HierarchyLevel::Chunk,1,0,0);CHECK_EQ(chunk.chunk.chunk.x,3);CHECK_EQ(chunk.block.x,5);CHECK_EQ(chunk.chunk.group.group.x,13);const auto group=offsetHierarchy(a,HierarchyLevel::Group,1,0,0);CHECK_EQ(group.chunk.group.group.x,14);CHECK_EQ(group.chunk.chunk.x,2);CHECK_EQ(group.block.x,5);const auto section=offsetHierarchy(a,HierarchyLevel::Section,1,0,0);CHECK_EQ(section.chunk.group.section.x,11);CHECK_EQ(section.chunk.group.group.x,13);CHECK_EQ(section.chunk.chunk.x,2);CHECK_EQ(section.block.x,5);const auto region=offsetHierarchy(a,HierarchyLevel::Region,1,0,0);CHECK_EQ(region.chunk.group.region.x,8);CHECK_EQ(region.chunk.group.section.x,10);CHECK_EQ(region.chunk.group.group.x,13);CHECK_EQ(region.chunk.chunk.x,2);CHECK_EQ(region.block.x,5);const auto sector=offsetHierarchy(a,HierarchyLevel::Sector,1,0,0);CHECK_EQ(sector.chunk.group.sector.x,5);CHECK_EQ(sector.chunk.group.region.x,7);CHECK_EQ(sector.chunk.group.section.x,10);CHECK_EQ(sector.chunk.group.group.x,13);CHECK_EQ(sector.chunk.chunk.x,2);CHECK_EQ(sector.block.x,5);}

TEST_CASE(hierarchy_navigation_carries_without_losing_local_position){using namespace world;BlockAddress a{};a.chunk.group.sector.x=12;a.chunk.group.region.x=REGIONS_PER_SECTOR_EDGE-1;a.chunk.group.section.x=SECTIONS_PER_REGION_EDGE-1;a.chunk.group.group.x=GROUPS_PER_SECTION_EDGE-1;a.chunk.chunk.x=CHUNKS_PER_GROUP_EDGE-1;a.block.x=9;const auto chunk=offsetHierarchy(a,HierarchyLevel::Chunk,1,0,0);CHECK_EQ(chunk.chunk.chunk.x,0);CHECK_EQ(chunk.chunk.group.group.x,0);CHECK_EQ(chunk.chunk.group.section.x,0);CHECK_EQ(chunk.chunk.group.region.x,0);CHECK_EQ(chunk.chunk.group.sector.x,13);CHECK_EQ(chunk.block.x,9);const auto region=offsetHierarchy(a,HierarchyLevel::Region,1,0,0);CHECK_EQ(region.chunk.group.region.x,0);CHECK_EQ(region.chunk.group.sector.x,13);CHECK_EQ(region.chunk.group.section.x,SECTIONS_PER_REGION_EDGE-1);CHECK_EQ(region.chunk.group.group.x,GROUPS_PER_SECTION_EDGE-1);CHECK_EQ(region.chunk.chunk.x,CHUNKS_PER_GROUP_EDGE-1);CHECK_EQ(region.block.x,9);}

TEST_CASE(hierarchy_navigation_rejects_sector_overflow){using namespace world;BlockAddress a{};a.chunk.group.sector.x=std::numeric_limits<std::int64_t>::max();BlockAddress out{};CHECK(!tryOffsetHierarchy(a,HierarchyLevel::Sector,1,0,0,out));}
TEST_CASE(hierarchy_navigation_moves_negative_across_origin){using namespace world;BlockAddress a{};a.block.x=3;const auto b=offsetHierarchy(a,HierarchyLevel::Chunk,-1,0,0);CHECK_EQ(b.chunk.group.sector.x,-1);CHECK_EQ(b.chunk.group.region.x,REGIONS_PER_SECTOR_EDGE-1);CHECK_EQ(b.chunk.group.section.x,SECTIONS_PER_REGION_EDGE-1);CHECK_EQ(b.chunk.group.group.x,GROUPS_PER_SECTION_EDGE-1);CHECK_EQ(b.chunk.chunk.x,CHUNKS_PER_GROUP_EDGE-1);CHECK_EQ(b.block.x,3);}
int main(){return test::runAll();}
